@extends('v2.front.templates.master')

@section('title', 'Security - Your Account - Project City Build')
@section('description', '')

@section('body')
    <header class="image-header">
        <div class="container">
            <h1>Your Account</h1>
        </div>
    </header>

    <main class="page settings">
        @include('v2.front.pages.account.components.account-sidebar')
        <div class="settings__content">
            <div class="settings__section">
                <h2 class="settings__section-heading">Password</h2>
                <p class="settings__description">TODO: i wanna move the password stuff here</p>
            </div>

            <div class="settings__section">
                <h2 class="settings__section-heading">2-Factor Authentication</h2>

                <p class="settings__description">2FA protects your account by requiring a one-time code generated by your phone to sign in.</p>


                @if(Session::get('mfa_setup_finished', false))
                    <div class="alert alert--success">
                        <h2><i class="fas fa-check"></i> 2FA Enabled</h2>
                        2FA has successfully been enabled on your account
                    </div>
                @endif
                @if(Session::get('mfa_disabled', false))
                    <div class="alert alert--success">
                        <h2><i class="fas fa-check"></i> 2FA Disabled</h2>
                        2FA has successfully been removed from your account
                    </div>
                @endif

                @if(Auth::user()->is_totp_enabled)
                    <div class="settings__security-twofa-status">
                        <p class="settings__security-twofa-status-enabled"><i class="fas fa-lock"></i> 2FA Enabled</p>
                        <p>You need to use your device or your backup code to sign in.</p>
                    </div>


                    <a href="{{ route('front.account.security.reset-backup') }}" class="button button--filled">Regenerate
                        Backup Code</a>
                    <a href="{{ route('front.account.security.disable') }}" class="button button--filled">Disable
                        2FA</a>
                @else
                    <div class="settings__security-twofa-status">
                        <p class="settings__security-twofa-status-not-enabled"><i class="fas fa-unlock"></i> 2FA Not Enabled</p>
                        <p>You don't have 2FA enabled yet. It's optional, but it will help protect your account.</p>
                    </div>

                    <form action="{{ route('front.account.security.start') }}" method="post">
                        @csrf
                        <button class="button button--filled button--has-icon-right">
                            Set Up
                            <i class="fas fa-chevron-right"></i>
                        </button>
                    </form>
                @endif
            </div>
        </div>
    </main>
@endsection
