name: Deploy

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      keep-releases:
        required: true
        type: number
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install PHP
        uses: ./.github/actions/install-php

      - name: Install Composer dependencies
        run: composer install

      - name: Deploy ${{ inputs.branch }} branch
        uses: deployphp/action@6242095e7207facf115ac4439760356bc52760ac
        env:
          DEPLOY_BRANCH: ${{ inputs.branch }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_DISCORD_CHANNEL_ID: ${{ secrets.DEPLOY_DISCORD_CHANNEL_ID }}
          DEPLOY_DISCORD_CHANNEL_TOKEN: ${{ secrets.DEPLOY_DISCORD_CHANNEL_TOKEN }}
        with:
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          dep: "deploy -o keep_releases=${{ inputs.keep-releases }}"

