name: Run API tests

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.3
        env:
          MYSQL_DATABASE: testing
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=3

      steps:
        - uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.3
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
            coverage: none

        - name: Get Composer cache directory
          id: get-composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Restore Composer cache
          id: composer-cache
          uses: actions/cache@v3
          with:
            path: ${{ steps.get-composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-v3-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-

        - name: Install Composer dependencies
          run: composer install --prefer-dist --ignore-platform-reqs --no-interaction

        - name: Prepare .env file
          run: cp .env.example .env

        - name: Prepare Laravel
          run: |
            php artisan key:generate
            chmod -R 777 storage bootstrap/cache

        - name: Prepare database
          env:
            DB_HOST: 127.0.0.1
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
          run: php artisan migrate

        - name: PHPUnit
          env:
            DB_HOST: 127.0.0.1
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
          run: php artisan test