name: Build containeres

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: |
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            laravelsail/php81-composer:latest \
            composer validate && composer install --ignore-platform-reqs --no-interaction --no-scripts

      - name: Prepare .env file
        run: cp .env.ci .env

      - name: Build Docker containers
        run: ./vendor/bin/sail up -d

      - name: Install npm dependencies
        run: ./vendor/bin/sail npm ci

      - name: Build front-end assets
        run: ./vendor/bin/sail npm run prod

      - name: Prepare Laravel
        run: |
          ./vendor/bin/sail php artisan key:generate
          chmod -R 777 storage bootstrap/cache

      - name: Prepare database
        run: ./vendor/bin/sail php artisan migrate
