name: Deployment

on:
  push:
    branches:
      - main
      - release

concurrency: deploy_production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@6242095e7207facf115ac4439760356bc52760ac
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          dep: deploy
          keep_releases: 5

