name: Deploy Dev

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/__deploy.yml
    secrets: inherit
    with:
      environment: dev
      branch: main
      keep-releases: 3

