name: PHP (E2E Tests)

on: push

jobs:
  build:
    uses: projectcitybuild/web/.github/workflows/build.yml@master

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run E2E tests
        run: ./vendor/bin/sail test --testsuite=E2E
