name: Create release PR

on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Sync branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Open pull request
        id: pull
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "release"
          PULL_REQUEST_IS_DRAFT: true
          PULL_REQUEST_TITLE: "Release"
          PULL_REQUEST_BODY: "Merge this branch when you're ready to release the next version. \n\n:warning: **Please add `#major`, `#minor` or `#patch` to the commit message, or else the version may be bumped incorrectly**"
